### ISSUE TITLE
Sensitive case in the search of payment mode

### ISSUE THREAD

**Issue by alexandre-mbm** [sabas/suosm#10]
It do not must be sensitive, like in the search of categories.

**Comment by sabas** [comment]
I try fixing it doing the loop as in the categories part.

**Comment by sabas** [comment]
https://github.com/sabas/suosm/blob/gh-pages/js/site.js#L44 Now writing in all lower case works..

**Comment by alexandre-mbm** [comment]
Thanks! :+1: I see 98e96448c6414ca99d20bad89187a337da3d0059.

**Comment by alexandre-mbm** [comment]
I did `git cherry-pick` + `git commit --amend`. :8ball:
