### ISSUE TITLE
Key:wheelchair

### ISSUE THREAD

**Issue by alexandre-mbm** [sabas/suosm#11]
See alexandre-mbm/osm-zapto#4. Do you intend to resolve this issue in the italian version? I'm thinking of using brief translations with detailed tooltips, but do not know if this is technically viable.

**Comment by sabas** [comment]
@alexandre-mbm I had added the field "Acessibilidade para cadeirantes" to replicate the tags of Wheelmap, so imo is translatable 1:1 with the wheelchair tag (I thought to give the user a plain language version of the tag, but the value posted in the note is the OSM value https://github.com/alexandre-mbm/osm-zapto/blob/gh-pages/index.html#L93)... What's the issue?

**Comment by alexandre-mbm** [comment]
@sabas, some people find those descriptions are insufficient.

**Comment by sabas** [comment]
from which side? those who enter the note or the mappers? :)

**Comment by alexandre-mbm** [comment]
Who enter the note. See  [Pt-br:Key:wheelchair](http://wiki.openstreetmap.org/wiki/Pt-br:Key:wheelchair) please.

**Comment by sabas** [comment]
I'm open to suggestions!

**Comment by alexandre-mbm** [comment]
Suggestion 1: put these three details of each option in floating boxes (tooltips).
Suggestion 2: create a icon "Help" — blue symbol `?` — for the field, with floating box (details).

Either 1 or 2.

**Comment by alexandre-mbm** [comment]
@sabas, if you don't think this is important for the italian version, maybe I can do it in the brazilian version only.

**Comment by sabas** [comment]
I see what you mean! If you meanwhile find a way to do it please let me know. :)

**Comment by alexandre-mbm** [comment]
Do you will leave the issue?

**Comment by alexandre-mbm** [comment]
I see [simple](http://jsfiddle.net/wdm954/9jaZL/7/) ([including color](http://jsbin.com/owupil/10/edit)) and [very simple](http://jsfiddle.net/booyaa/tA7Zh/) — and [pure CSS](http://www.handycss.com/how/how-to-create-a-pure-css-tooltip/) — examples that are not the case. But I see also lists with [15](http://www.webdesignbooth.com/15-jquery-plugins-to-create-an-user-friendly-tooltip/), [20](http://visionwidget.com/jquery-tooltip-plugins.html), [25](http://speckyboy.com/2009/09/16/25-useful-jquery-tooltip-plugins-and-tutorials/), [30](http://www.1stwebdesigner.com/css/stylish-jquery-tooltip-plugins-webdesign/) examples more complex, and [jQueryTOOLS TOOLTIP Web Fundamentals](http://jquerytools.org/demos/tooltip/any-html.html).

I'll still check licensing issues, for example, but I'm tending to use a **[modal tootip](http://craigsworks.com/projects/qtip/demos/effects/modal#)** from a help icon like the following.

![form-edited](https://cloud.githubusercontent.com/assets/957501/2873453/0d1b95d2-d3ac-11e3-8775-517c03350484.png)

I will go to use [File:Ambox blue question.svg](https://commons.wikimedia.org/wiki/File:Ambox_blue_question.svg) that is in public domain.

**Comment by alexandre-mbm** [comment]
I am with a problem. The lib qTip requires `jquery-1.3.2.min.js` and the suosm's marker works only with `jquery-1.9.1.min.js`. Do you know the cause? The console talks something on [`//@` and `//#`](https://groups.google.com/forum/#!topic/mozilla.dev.js-sourcemap/4uo7Z5nTfUY)...

**Comment by alexandre-mbm** [comment]
See qTip2/qTip2#459. I must to continue using the `jquery-1.9.1.min.js` but with the [`jquery-migrate` "solution"](http://blog.jquery.com/2013/01/15/jquery-1-9-final-jquery-2-0-beta-migrate-final-released/) (GitHub: [jquery/jquery-migrate](/jquery/jquery-migrate)). Because [jQuery.browser() was removed in the 1.9 version](http://jquery.com/upgrade-guide/1.9/#jquery-browser-removed).

**Comment by sabas** [comment]
I didn't see the image yet, nice!
Add jq migrate via cdn if possible, hoping jqtip guys upgrade their jquery..

**Comment by alexandre-mbm** [comment]
Now the problem is the modal note be lot great for windows in 800x600. ~~I will try to test small notes for each item of the select box. I will make push of branches today.~~ I adapted the style for 800x600.

**Comment by alexandre-mbm** [comment]
**Done!** Commit 25313848ad2c29b6fdf8abc4b99af6bdf38b5592.

**Comment by sabas** [comment]
Awesome solution! I will work on it to port in italian :)

**Comment by alexandre-mbm** [comment]
When testing, keep in mind that the AJAX request only works on a web server.

**Comment by sabas** [comment]
Closed by 20a9b1f7f0bf9dbdbbc765c0785136c7124a4794

**Comment by sabas** [comment]
Thanks @alexandre-mbm !
