### ISSUE TITLE
problemi per su.openstreetmap.it su vari browser / problems for su.openstreetmap.it on various browsers

### ISSUE THREAD

**Issue by damjang** [sabas/suosm#27]
Ho trovato che su vari browsers (palemoon, internet explorer, chrome, edge) nella parte di
inserimento dettagli nelle categorie non trova niente (Nessuna corrispondenza trovata), stessa cosa in Accessibilità in sedia a rotelle ed anche in Modalità di pagamento accettate niente ed in più i due radio
button per il covid-19 sotto sono vuoti e senza descrizione.
Ho scoperto che se clicco sul link della lingua a destra sopra (https://su.openstreetmap.it/?setLng=it-IT) poi funziona tutto bene. Quindi è un problema di settaggio della lingua di default.

**Comment by fansanelli** [comment]
Ciao.
Non credo di riuscire a replicare l'errore... Hai bloccato i cookies?
Francesco

**Comment by damjang** [comment]
No. Da browser appena lanciato vado su su.openstreetmap.it, digito un place e vado in seconda pagina e vedo questo: http://www.damjan.net/tmp/su.openstreetmap.it.01.png
Forse è un problema perché ho il browser/windows impostato su una lingua che non è ne italiano ne inglese?

**Comment by fansanelli** [comment]
Potrebbe essere un buon indizio! Domani sera provo ad indagare
