### ISSUE TITLE
add CAP hint

### ISSUE THREAD

**Issue by cortesimone** [sabas/suosm#9]
please provide a CAP - Codice di Avviamento Postale hint in the form, in order to suggest to the user our need to get that information.

the current: Viale Brigate Partigiane, Genova
should read: Viale Brigate Partigiane, 16129, Genova

**Comment by sabas** [comment]
okay, I will do IT this evening..

**Comment by sabas** [comment]
@cortesimone Wait a moment, the first field gets considered as address but it's also used for geocoding. What about if the address doesn't exist or no address is inputted? We should provide a precise address form in the second  step?

**Comment by sabas** [comment]
Fixed by 4f9277ce95fa8d6ca7390e3ed3cdde5248b325d0
